- shell:
    -
        command: [/bin/sh configs/git/install.sh]
        stdin: true
        stdout: true
        stderr: true
- link:
    ~/.gitconfig: configs/git/.gitconfig
    /usr/local/bin/git-st: configs/git/git-st
