- shell:
    -
        command: [/bin/sh configs/macos/install.sh]
        stdin: true
        stdout: true
        stderr: true
- link:
    ~/.hushlogin: configs/macos/.hushlogin
    ~/.mailcap: configs/macos/.mailcap
    ~/.config/tuir/tuir.cfg: configs/macos/tuir.cfg
