- shell:
    -
        command: [/bin/sh configs/neovim/install.sh]
        stdin: true
        stdout: true
        stderr: true
- link:
    ~/.eslintrc.js: configs/neovim/.eslintrc.js
    ~/.tern-config: configs/neovim/.tern-config
    ~/.config/nvim/init.vim: configs/neovim/init.vim
