#!/bin/sh
IFS=
diff="$(git diff --color --stat HEAD | sed '$d; s/^ //' | cut -d '|' -f 2)"
status="$(git -c color.status=always status -sb)"

IFS=$'\n' status=($status)
IFS=$'\n' diff=($diff)

branch=$(echo "${status[0]}" | cut -d ' ' -f 2-)
echo $branch

for i in $(seq 1 ${#status[@] - 1})
do
    currStatus=${status[i]}
    currDiff=${diff[i - 1]}
    if [ ! -z $currDiff ]
    then
        currDiff=" |${diff[i - 1]}"
    fi
    if [ $i -ne ${#status[@] - 1} ]
    then
        printf "%*s%s\n" -30 "${currStatus}" "${currDiff}"
    fi
done
