#!/bin/sh
IFS=
status="$(git -c color.status=always status -sb)"
if [ $? -ne 0 ]
then
    exit 1
fi

diff="$(git diff --color --stat HEAD 2> /dev/null | sed '$d; s/^ //' | cut -d '|' -f 2)"

IFS=$'\n' status=($status)
IFS=$'\n' diff=($diff)

branch=$(echo "${status[0]}" | cut -d ' ' -f 2-)
echo $branch

len=-1
for i in $(seq 1 $(( ${#status[@]} - 1)))
do
    if [ ${#status[i]} -gt $len ]
    then
        len=${#status[i]}
    fi
done
(( len *= -1 ))

for i in $(seq 1 $(( ${#status[@]} - 1)))
do
    currStatus=${status[i]}
    currDiff=${diff[i - 1]}
    if [ ! -z $currDiff ]
    then
        currDiff="|${currDiff}"
    fi
    printf "%*s  %s\n" $len "${currStatus}" "${currDiff}"
done
