before_script:
    - sudo spctl --master-disable
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

install:
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'
          when: always
        - if: $CI_COMMIT_BRANCH != 'master'
          when: never
    script:
        - ./install-standalone git
        - ./install-standalone iterm2
        - ./install-standalone macos
        - ./install-standalone neovim
        - ./install-standalone tmux
        - ./install-standalone zsh
