before_script:
  - sudo spctl --master-disable
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

stages:
  - install_git
  - install_iterm2
  - install_macos
  - install_neovim
  - install_tmux
  - install_zsh

install_git:
  stage: install_git
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone git

install_iterm2:
  stage: install_iterm2
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone iterm2

install_macos:
  stage: install_macos
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone macos

install_neovim:
  stage: install_neovim
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone neovim

install_tmux:
  stage: install_tmux
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone tmux

install_zsh:
  stage: install_zsh
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - ./install-standalone zsh
