#!/usr/bin/env bash
which -s brew
if [[ $? != 0 ]] ; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    brew update
fi
./install-standalone git && \
./install-standalone iterm2 && \
./install-standalone macos && \
./install-standalone neovim && \
./install-standalone tmux && \
./install-standalone vim && \
./install-standalone zsh
