#!/usr/bin/env bash
sudo spctl --master-disable

which -s brew
if [[ $? != 0 ]] ; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    brew update
fi

./install-standalone git && \
./install-standalone iterm2 && \
./install-standalone macos && \
./install-standalone neovim && \
./install-standalone tmux && \
./install-standalone zsh
