#!/bin/zsh

DIR=$(dirname $0)
STASH=$(git -C $DIR stash)
git -C $DIR fetch && git -C $DIR pull --rebase
if [ "${STASH}" != "No local changes to save" ]; then
    git -C $DIR stash pop
fi

# Update and upgrade latest brew packages
brew update && brew outdated && brew upgrade --no-quarantine && brew cleanup
brew upgrade --cask --greedy --no-quarantine && brew cleanup
brew autoremove

# Update npm packages
npm update -g

# Update neovim
git submodule update configs/neovim
nvim -c "lua require('lazy').sync({wait = true})" +qa

# Update zgenom
source "${HOME}/.zgenom/zgenom.zsh" && zgenom update

# Update tmux
~/.tmux/plugins/tpm/scripts/update_plugin.sh

# Clear all cache
rm -rf ~/.npm ~/Library/Caches/pip $(brew --cache)

# Get new shell
exec zsh
