#!/bin/zsh

DIR=$(dirname $0)
git -C $DIR fetch && git -C $DIR pull --rebase

# Update and upgrade latest brew packages
brew update && brew outdated && brew upgrade --no-quarantine && brew cleanup
brew upgrade --cask --greedy --no-quarantine && brew cleanup
brew autoremove

# Update npm packages
npm update -g

# Update neovim
nvim --headless "+Lazy! sync" +qa

# Update zgenom
source "${HOME}/.zgenom/zgenom.zsh" && zgenom update

# Clear all cache
rm -rf ~/.npm ~/Library/Caches/pip $(brew --cache)

# Get new shell
exec zsh
