name: MacOS Dotfiles CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v1
            - name: Execute full install
              run: ./install-all
